# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='ip',
        ),
        migrations.AddField(
            model_name='address',
            name='session_key',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
