# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='ip',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
