# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170823_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
