# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170908_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
    ]
