# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170724_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
