# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 14:24
from __future__ import unicode_literals

import app.fields.piece_date
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_exhibition_facebook_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='date',
            field=app.fields.piece_date.PieceDateField(null=True),
        ),
    ]
