# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='String',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
            ],
        ),
    ]
