# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170727_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
