# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170728_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='piece',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
