# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
