# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_order_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='braintree_transaction_id',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
