# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_exhibition'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
