# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 14:14
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_exhibition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='exhibitions/1w'),
        ),
    ]
