# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170826_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='ip',
        ),
        migrations.AddField(
            model_name='basket',
            name='session_key',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
