# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 11:01
from __future__ import unicode_literals

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170730_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=app.fields.MultisizeImageField(null=True, root_dir='exhibitions', widths=[150, 300]),
        ),
    ]
