# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170731_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='image',
        ),
    ]
