# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170826_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
