# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 13:11
from __future__ import unicode_literals

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_exhibition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='image',
            field=app.fields.MultisizeImageField(null=True, root_dir='exhibitions', widths=[150, 300]),
        ),
    ]
