# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:39
from __future__ import unicode_literals

import app.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_exhibition_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='image',
            field=app.fields.MultisizeImageField(null=True, root_dir='pieces', widths=[-1, 720, 360, 180]),
        ),
    ]
