# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 21:01
from __future__ import unicode_literals

import app.fields.exhibition_datetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170807_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='datetime',
            field=app.fields.exhibition_datetime.ExhibitionDateTimeField(null=True),
        ),
    ]
