# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170808_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='index_in_list',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='piece',
            unique_together=set([]),
        ),
    ]
