# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 19:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
