# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20170809_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='basket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pieces', to='app.Basket'),
        ),
    ]
