# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('app', '0022_pendinguser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendinguser',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='PendingUser',
        ),
    ]
