# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_pendinguser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendinguser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
