# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_emailchange'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailchange',
            old_name='new_address',
            new_name='new_email',
        ),
    ]
